require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end

desc "Start the server"
task :server do  
  if ActiveRecord::Base.connection.migration_context.needs_migration?
    puts "Migrations are pending. Make sure to run `rake db:migrate` first."
    return
  end

  # rerun allows auto-reloading of server when files are updated
  # -b runs in the background (include it or binding.pry won't work)
  exec "bundle exec rerun -b 'rackup config.ru'"
end

post '/baked_goods' do
  baked_good = BakedGood.create(
    name: params[:name],
    price: params[:price],
    bakery_id: params[:bakery_id]
  )
  baked_good.to_json
end

patch '/bakeries/:id' do
  bakery = Bakery.find(params[:id])
  bakery.update(
    name: params[:name]
  )
  bakery.to_json
end

delete '/baked_goods/:id' do
  baked_good = BakedGood.find(params[:id])
  baked_good.destroy
  baked_good.to_json
end

end